#!/bin/bash
set -e

MY_PATH="`dirname \"$0\"`"

if [[ ! "$OSTYPE" == "darwin"* ]]; then
  exit
fi

# set homebrew cask options
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

if ! which brew >/dev/null; then
  echo installing brew…
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

if [ ! -f ~/brew-last-update.tmp ] || [ `stat -f "%Sm" -t "%Y%m%d" ~/brew-last-update.tmp` -ne `date +%Y%m%d` ]; then
  echo brew update…
  brew update
  touch ~/brew-last-update.tmp
fi

if [ ! -d /opt/homebrew-cask/ ]; then
  brew bundle "$MY_PATH/cask/Brewfile" 2>&1 | sed -e '/[Aa]lready tapped/d' -e '/[Aa]lready installed/d' -e '/[Aa]lready linked/d'
fi
