# install brew cask (see http://gillesfabio.github.io/homebrew-cask-homepage/)
# cask allows you to install GUI apps using brew
tap caskroom/cask
install brew-cask

# install alfred and tell him about cask apps
cask install alfred
cask alfred link
