#!/bin/bash
set -e

MY_PATH="`dirname \"$0\"`"
ABSOLUTE_PATH=$(cd $MY_PATH; pwd)

git config --global alias.s status
git config --global alias.co checkout
git config --global alias.a "!git add -u && git add . && git status"
git config --global alias.amend "commit --amend"

# set up scripts in commands folder as aliases
for file in $MY_PATH/commands/*
do
  command=$(basename $file)
  git config --global alias.$command "!sh $ABSOLUTE_PATH/commands/$command"
done
