#!/bin/bash
set -e

git config --global alias.s status
git config --global alias.feature "!f() { git fetch upstream && git checkout -b feature/$1 upstream/master; }; f"
git config --global alias.a "!git add -u && git add . && git status"
git config --global alias.c "commit -m"
git config --global alias.amend "commit --amend"
git config --global alias.up "!git fetch upstream && git rebase upstream/master"
