#!/bin/sh

cli=/Applications/KeyRemap4MacBook.app/Contents/Applications/KeyRemap4MacBook_cli.app/Contents/MacOS/KeyRemap4MacBook_cli

$cli set remap.pcstyle_command_Fn_shift_Fn 1
/bin/echo -n .
$cli set repeat.wait 20
/bin/echo -n .
$cli set remap.pc_printscreen_scrolllock_pause_to_volume_controls 1
/bin/echo -n .
$cli set remap.winstyle_redo 1
/bin/echo -n .
$cli set remap.pclikepageupdown_except_emacs 1
/bin/echo -n .
$cli set remap.pclikehomeend 1
/bin/echo -n .
$cli set remap.windows4mac 1
/bin/echo -n .
$cli set remap.pc_style_copy_paste 1
/bin/echo -n .
$cli set repeat.initial_wait 300
/bin/echo -n .
/bin/echo
