#!/bin/bash
set -e

if [[ ! "$OSTYPE" == "darwin"* ]]; then
  exit
fi

MY_PATH="`dirname \"$0\"`"

/Applications/KeyRemap4MacBook.app/Contents/Applications/KeyRemap4MacBook_cli.app/Contents/MacOS/KeyRemap4MacBook_cli export > $MY_PATH/exported_mappings
