#!/bin/bash
set -e

if [[ ! "$OSTYPE" == "darwin"* ]]; then
  exit
fi

MY_PATH="`dirname \"$0\"`"

sh $MY_PATH/../brew/init
sh $MY_PATH/../brew/bundle $MY_PATH/Brewfile

# run exported mappings (to update with your current settings use: sh export)
sh $MY_PATH/exported_mappings
