#!/bin/bash
set -e

from="master"
if [ $1 == 'from' ]; then
  name=$(echo "${*:3}" | sed 's/[^A-Za-z0-9/]/-/g')
  from="$2"
else
  name=$(echo "$*" | sed 's/[^A-Za-z0-9/]/-/g')
fi

if [ ! -z "$(git branch --list $name)" ]; then
  git checkout $name
else
  if [ -z $(git remote | grep upstream) ]; then
    # no fork
    remote="origin"
  else
    # on a fork
    remote="upstream"
  fi
  git fetch $remote
  if [ ! -z "$(git branch -ar --list $remote/$name)" ]; then
    echo "found branch $name at $remote/$name..."
    git checkout -b $name $remote/$name
  else
    echo "creating branch $name based on $remote/$from..."
    git checkout -b $name $remote/$from
  fi
fi
