#!/bin/bash
set -e

if [ -z $(git remote | grep upstream) ]; then
  echo "forking...";
  git fork
fi

name=$(echo "$*" | sed 's/[^A-Za-z09]/-/g')

if [ ! -z "$(git branch --list feature/$name)" ]; then
  git checkout feature/$name
else
  echo "creating feature branch $name..."
  git fetch upstream
  git checkout -b feature/$name upstream/master
fi
