#!/bin/bash
set -e

name=$(echo "$*" | sed 's/[^A-Za-z0-9]/-/g')

if [ ! -z "$(git branch --list feature/$name)" ]; then
  git checkout feature/$name
else
  if [ -z $(git remote | grep upstream) ]; then
    # no fork
    remote="origin"
  else
    # on a fork
    remote="upstream"
  fi
  git fetch $remote
  if [ ! -z "$(git branch -ar --list $remote/feature/$name)" ]; then
    echo "found shared feature branch $name..."
    git checkout -b feature/$name $remote/feature/$name
  else
    echo "creating feature branch $name..."
    git checkout -b feature/$name $remote/master
  fi
fi
