#!/bin/bash
set -e

if [ -z $(git remote | grep upstream) ]; then
  echo "forking...";
  git fork
fi

name=$(echo "$*" | sed 's/[^A-Za-z0-9]/-/g')

if [ ! -z "$(git branch --list feature/$name)" ]; then
  git checkout feature/$name
else
  git fetch upstream
  if [ ! -z "$(git branch -ar --list upstream/feature/$name)" ]; then
    echo "found shared feature branch $name..."
    git checkout -b feature/$name upstream/feature/$name
  else
    echo "creating feature branch $name..."
    git checkout -b feature/$name upstream/master
  fi
fi
