#!/bin/bash
set -e

name=$(echo "$*" | sed 's/[^A-Za-z0-9]/-/g')

if [ ! -z "$(git branch --list hotfix/$name)" ]; then
  git checkout hotfix/$name
else
  if [ -z $(git remote | grep upstream) ]; then
    # no fork
    remote="origin"
  else
    # on a fork
    remote="upstream"
  fi
  git fetch $remote production
  if [ ! -z "$(git branch -ar --list upstream/hotfix/$name)" ]; then
    echo "found shared hotfix branch $name..."
    git checkout -b hotfix/$name upstream/hotfix/$name
  else
    echo "creating hotfix branch $name..."
    git checkout -b hotfix/$name upstream/production
  fi
fi
