#!/bin/bash
set -e

if [ -z $(git remote | grep upstream) ]; then
  echo "upstream not found, fork first" 1>&2;
  return 1
fi

git push origin

title="$*"

if [ -z "$title" ]; then
  title=$(git log -1 --pretty=%B)
fi

hub pull-request -m "$title"
