#!/bin/bash
set -e

if which ansible >/dev/null; then
  exit 0
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  echo OS not supported
  exit 1
elif [[ "$OSTYPE" == "darwin"* ]]; then

  MY_PATH="`dirname \"$0\"`"
  sh $MY_PATH/../brew/init

  echo installing ansible…
  brew install ansible

elif [[ "$OSTYPE" == "cygwin" ]]; then
  echo OS not supported
  exit 1
elif [[ "$OSTYPE" == "win32" ]]; then
  echo OS not supported
  exit 1
else
  echo OS not supported
  exit 1
fi

echo ansible ready
